import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const html=readFileSync(new URL('./index.html',import.meta.url),'utf8');
function tela(){
 const nodes=new Map<string,any>(),pedidos:any[]=[];const node=(id:string)=>{if(!nodes.has(id))nodes.set(id,{value:'',hidden:false,disabled:false,textContent:'',children:[],handlers:{},addEventListener(e:string,h:any){this.handlers[e]=h;},replaceChildren(...c:any[]){this.children=c;},appendChild(c:any){this.children.push(c);},setAttribute(){}});return nodes.get(id);};
 const c=vm.createContext({sessaoAtual:{tokenAcesso:'jwt-real',usuario:{medicoId:'ignorado'}},document:{getElementById:node,createElement:()=>node('el'+nodes.size)},window:{location:{search:'',assign(){}},history:{}},URLSearchParams,console,fetch:async(url:string,options:any)=>{pedidos.push({url,options});return {ok:true,json:async()=>url.endsWith('/previa')?{ok:true,previaId:'prev-1',pacientes:[{linha:2,nome:'<img onerror=alert(1)>',cpf:null,email:null,telefone:'5511999999999',pendencias:[]}],limitado:false,linhasLidas:1}:url.endsWith('/importar')?{ok:true,criados:1,completados:0,semAlteracao:0,ignorados:[]}:{ok:true,configurado:true,iaConfigurada:true,conectado:true}};}});
 const trecho=html.match(/\/\/ INICIO GOOGLE PLANILHAS([\s\S]*?)\/\/ FIM GOOGLE PLANILHAS/)?.[1];assert.ok(trecho,'integração deve existir na Conta');vm.runInContext(trecho,c);
 return {c,node,pedidos};
}
test('Google Planilhas lê com sessão e só importa após confirmação separada',async()=>{const f=tela();f.node('inputPlanilhaGoogle').value='https://docs.google.com/spreadsheets/d/planilha-valida';f.node('selectAbaGoogle').value='0';await f.node('btnLerPlanilhaGoogle').handlers.click();assert.equal(f.pedidos.length,1);assert.equal(f.pedidos[0].options.headers.Authorization,'Bearer jwt-real');assert.equal(JSON.parse(f.pedidos[0].options.body).medicoId,undefined);assert.equal(f.node('btnImportarPlanilhaGoogle').disabled,false);await f.node('btnImportarPlanilhaGoogle').handlers.click();assert.equal(f.pedidos.length,2);assert.equal(JSON.parse(f.pedidos[1].options.body).previaId,'prev-1');assert.match(f.node('statusPlanilhaGoogle').textContent,/1/);});
test('células da planilha são texto, nunca HTML executável',async()=>{const f=tela();f.node('selectAbaGoogle').value='0';await f.node('btnLerPlanilhaGoogle').handlers.click();const tbody=f.node('previaPlanilhaGoogle');assert.equal(tbody.children[0].children[1].textContent,'<img onerror=alert(1)>');assert.equal(tbody.children[0].children[1].innerHTML,undefined);});
test('novo link invalida prévia e impede confirmar outra planilha por engano',async()=>{const f=tela();f.node('selectAbaGoogle').value='0';await f.node('btnLerPlanilhaGoogle').handlers.click();f.node('inputPlanilhaGoogle').handlers.input();assert.equal(f.node('btnImportarPlanilhaGoogle').disabled,true);await f.node('btnImportarPlanilhaGoogle').handlers.click();assert.equal(f.pedidos.length,1);});
